name: Generate Page
on:
    push:
        paths:
          - 'profile/**'
          - '.github/workflows/page.yml'

jobs:
    doc:
        name: Generate Page
        runs-on: ubuntu-latest
        
        steps:
            ## 检出工程
            - uses: actions/checkout@v3
              with: 
                submodules: 'true'

            ## 配置环境
            - run: git config --global user.name github-actions[bot]
            - run: git config --global user.email github-actions[bot]@users.noreply.github.com
            - run: git config --global --add safe.directory /github/workspace
          
            ## 暂存文档
            - run: mkdir ./swap
            - run: cp -r ./profile ./swap
            - run: git add ./swap
            - run: git stash save ./swap

            ## 切换分支
            - run: git fetch origin
            - run: git checkout gh-pages
            
            ## 清理目录
            - run: git rm -rf *
            - run: git commit -m '[Generate Page] commit cleanup'

            ## 弹出文档
            - run: git stash pop
            - run: git commit -m '[Generate Page] commit swap'
            - run: mv ./swap/* ./
            - run: git rm -rf ./swap
            
            ## 创建文件（使得页面文件包含'_'的可以被访问）
            - run: touch .nojekyll

            ## 创建CNAME
            - run: touch ./CNAME && echo -e "eframework.cn" >> ./CNAME
            
            ## 推送文档
            - run: git add ./
            - run: git commit -m '[Generate Page] commit product'
            - run: git push
